//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus_Toolkit {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class IcarusToolkit : global::System.Configuration.ApplicationSettingsBase {
        
        private static IcarusToolkit defaultInstance = ((IcarusToolkit)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IcarusToolkit())));
        
        public static IcarusToolkit Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDataPath {
            get {
                return ((string)(this["GameDataPath"]));
            }
            set {
                this["GameDataPath"] = value;
            }
        }
    }
}
